# configuration file for git-cliff
# see https://github.com/orhun/git-cliff#configuration-file

[changelog]
# changelog header
header = """
# Changelog

"""
# template for the changelog body
# https://tera.netlify.app/docs/#introduction
body = """
---
{% set platform = "https://github.com" -%}
{% set repository_url = platform ~ "/Mochi-Team/mochi" -%}
{% if version -%}
    ## [{{ version }}]({{ repository_url ~ "/releases/tag/" ~ version }}) - ({{ timestamp | date(format="%Y-%m-%d") }})
{% else -%}
    ## Unreleased
{% endif %}
{% for group, commits in commits | group_by(attribute="group") -%}
### {{ group | upper_first }}
    {% for commit in commits -%}
        {% if commit.scope -%}
        {% else -%}
            {% set commit_link = repository_url ~ "/commit/" ~ commit.id -%}
            {% set shorthand = commit.id | truncate(length=7, end="") -%}
            - {{ commit.message | upper_first }} [`{{ shorthand }}`]({{ commit_link }})
            {% if commit.breaking -%}
            {% raw %}  {% endraw %}- **BREAKING:** {{ commit.breaking_description }}
            {% endif -%}
        {% endif -%}
    {% endfor %}
    {% for scoped, commits in commits | group_by(attribute="scope") -%}
        **{{ scoped | upper_first }}**
        {% for commit in commits -%}
            {% set commit_link = repository_url ~ "/commit/" ~ commit.id -%}
            {% set shorthand = commit.id | truncate(length=7, end="") -%}
            - {{ commit.message | upper_first }} [`{{ shorthand }}`]({{ commit_link }})
            {% if commit.breaking -%}
            {% raw %}  {% endraw %}- **BREAKING:** {{ commit.breaking_description }}
            {% endif -%}
        {% endfor %}
    {% endfor -%}
{% endfor -%}

"""
# remove the leading and trailing whitespace from the template
trim = true
# changelog footer
footer = """
<!-- generated by git-cliff -->
"""

[git]
conventional_commits = true
filter_unconventional = true
split_commits = false
commit_preprocessors = [
    { pattern = '\((\w+\s)?#([0-9]+)\)', replace = "([#${2}](https://github.com/Mochi-Team/mochi/issues/${2}))"}, # replace issue numbers
    { pattern = "https://github.com/Mochi-Team/mochi/commit/([a-f0-9]{7})[a-f0-9]*", replace = "commit # [${1}](${0})"},
    { pattern = "([ \\n])(([a-f0-9]{7})[a-f0-9]*)", replace = "${1}commit # [${3}](https://github.com/Mochi-Team/mochi/commit/${2})"}
]
# regex for parsing and grouping commits
commit_parsers = [
    { message = "^feat", group = "Features"},
    { message = "^fix", group = "Bug Fixes"},
    { message = "^doc", group = "Documentation"},
    { message = "^perf", group = "Performance"},
    { message = "^refactor", group = "Refactor"},
    { message = "^style", group = "Styling"},
    { message = "^test", group = "Testing"},
    { message = "^chore\\(version\\)", skip = true},
    { message = "^chore", group = "Miscellaneous Tasks"},
    { message = "^ci", group = "Continuous Integration"},
    { message = "^wip", skip = true },
    { body = ".*security", group = "Security"},
]

protect_breaking_commits = false
filter_commits = false
tag_pattern = "[0-9]*"
skip_tags = ""
ignore_tags = ""
topo_order = false
sort_commits = "oldest"
